language: node_js
node_js:
  - "8.2.1"
jobs:
  include:
    - stage: deploy to development
      install:
      - npm install newman
      script:
      - echo devlopment
      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Development.postman_environment.json --global-var username=$clouduser --global-var password=$clouduserpass
    - stage: deploy to staging
      script: echo staging 
    - stage: deploy to production
      script: echo prod 
