language: node_js
node_js:
  - "8.2.1"
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: Deploy to WSO2 API Cloud 
      script:
      - bash test.sh || travis_terminate 1;
      - bash test2.sh || travis_terminate 1;
