language: node_js
node_js:
  - "8.2.1"
jobs:
  include:
    - stage: deploy to development
      install:
      - npm install newman
      before_script:
      - node --version
      - npm --version
      - node_modules/.bin/newman --version
      script:
      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Development.postman_environment.json --global-var username=$clouduser --global-var password=$clouduserpass
    - stage: deploy to staging
      script: echo two
    - stage: deploy to production
      script: skip
