language: node_js
node_js:
  - "8.2.1"
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: Deploy to WSO2 API Cloud 
      install:
      - npm install newman
      script:
      - java -version
      - mvn -version
      - cd Hello-Service
      - mvn clean install 
      - echo "Development API Runtime"
#      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Development.postman_environment.json --global-var username=$clouduser --global-var password=$clouduserpass
#      - echo "Staging API Runtime"
#      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Staging.postman_environment.json --global-var username=$staging-clouduser --global-var password=$staging-clouduserpass 
#      - echo "Production API Runtime"
#      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Production.postman_environment.json --global-var username=$production-clouduser --global-var password=$production-clouduserpass 
