    - language: java 
      jdk:
       - oraclejdk8
      node_js:
      - "8.2.1"
      install: 
      - "npm install newman"
      after_success:
       - echo "JAVA Runtime" 
       - java -version 
