language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json --global-var username=$clouduser --global-var password=$clouduserpass 
